- name: Uninstall NGINX
  hosts: frontend
  become: yes
  tasks:
    - name: Stop nginx service if running
      ansible.builtin.service:
        name: nginx
        state: stopped
      ignore_errors: yes

    - name: Uninstall nginx package
      ansible.builtin.package:
        name: nginx
        state: absent
